{% set python_min = '3.11' %}
{% set name = "smee" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/openforcefield/smee/archive/{{ version }}.tar.gz
  sha256: 5ec61e50b4e3f3839221780715d8219c56ed60ee67f5db6e430f8beb6ceeef28

build:
  number: 1

outputs:
  - name: {{ name|lower }}-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=61.0
        - setuptools_scm >=8
      run:
        - python >={{ python_min }}
        - openff-units
        - openff-toolkit-base >=0.9.2
        - openff-interchange-base >=0.3.17
        - pytorch  # [unix]
        - __unix  # [unix]
    test:
      requires:
        - python {{ python_min }}
      imports:
        - smee

  - name: {{ name|lower }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('smee-base', exact=True) }}
        # md simulations
        - openmm
        - packmol
        - numpy
        - msgpack-python
        - pydantic
        - pydantic-units
        # included for convenience so that the openff toolkit can
        # parameterize molecules without needing extra installs
        - rdkit
        - __unix  # [unix]
        - nnpops
    test:
      requires:
        - python {{ python_min }}
      imports:
        - smee

about:
  home: https://github.com/openforcefield/smee
  summary: 'Differentiably evaluate energies using SMIRNOFF force fields'
  description: |
    A framework that aims to offer a simple API for differentiably evaluating 
    the energy of SMIRNOFF force fields applied to molecules using pytorch.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://github.com/openforcefield/smee
  dev_url: https://github.com/openforcefield/smee

extra:
  recipe-maintainers:
    - SimonBoothroyd
    - j-wags
    - lilyminium
    - mattwthompson
    - Yoshanuikabundi
    - fjclark
